# Generated by Django 6.0 on 2026-01-16 10:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la marque')),
                ('country', models.CharField(max_length=100, verbose_name="Pays d'origine")),
                ('founded_year', models.IntegerField(verbose_name='Année de fondation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description technique')),
            ],
            options={
                'verbose_name': 'Complication',
                'verbose_name_plural': 'Complications',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Nom du modèle')),
                ('reference_number', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (€)')),
                ('case_diameter', models.IntegerField(validators=[django.core.validators.MinValueValidator(20)], verbose_name='Diamètre (mm)')),
                ('movement_type', models.CharField(choices=[('AUTO', 'Automatique'), ('MANUAL', 'Manuel'), ('QUARTZ', 'Quartz'), ('SOLAR', 'Solaire')], max_length=10, verbose_name='Type de mouvement')),
                ('case_material', models.CharField(choices=[('STEEL', 'Acier'), ('GOLD', 'Or'), ('TITANIUM', 'Titane'), ('CERAMIC', 'Céramique'), ('PLATINUM', 'Platine'), ('BRONZE', 'Bronze')], max_length=10, verbose_name='Matériau du boîtier')),
                ('water_resistance', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Étanchéité (m)')),
                ('description', models.TextField(verbose_name='Description / Histoire')),
                ('image', models.ImageField(blank=True, null=True, upload_to='watches/', verbose_name='Photo')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro de série')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='watches.brand', verbose_name='Marque')),
                ('complications', models.ManyToManyField(blank=True, related_name='watches', to='watches.complication', verbose_name='Complications')),
            ],
            options={
                'verbose_name': 'Montre',
                'verbose_name_plural': 'Montres',
                'ordering': ['-created_at'],
            },
        ),
    ]
